# Generated by Django 5.1 on 2026-08-13 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='commet',
            new_name='comment',
        ),
    ]
