# Generated by Django 5.1 on 2026-09-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_released',
            field=models.BooleanField(default=False),
        ),
    ]
