# Generated by Django 5.1 on 2026-07-10 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_brand_logo_category_description_category_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productattribute',
            options={'verbose_name': 'Характеристика', 'verbose_name_plural': 'Характеристики'},
        ),
    ]
