# Generated by Django 6.1.1 on 2026-09-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_productattribute_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='attribute_type',
            field=models.CharField(choices=[('spec', 'Specification'), ('feature', 'Key Feature')], default='spec', max_length=20),
        ),
    ]
