# Generated by Django 6.1.1 on 2026-09-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productattribute_attribute_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='attribute_type',
            field=models.CharField(choices=[('primary', 'Primary Specification'), ('secondary', 'Secondary Specification'), ('feature', 'Key Feature')], default='secondary', max_length=20, verbose_name='Тип'),
        ),
    ]
